# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: Org Stars Daily

on:
  schedule:
    - cron: "7 2 * * *" # daily at 02:07 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install requests
      - name: Count stars
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT: data/org_stars.json
        run: python org_stars.py
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "UltralyticsAssistant"
            git config user.email "web@ultralytics.com"
            git add data/org_stars.json
            git commit -m "Update org stars"
            git push
          fi
